//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chat_Together.src.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Message_Record = new HashSet<Message_Record>();
        }
    
        public string UserName { get; set; }
        public string Password { get; set; }
        public int id { get; set; }
        public bool HasAdminPrivileges { get; set; }
        public byte[] ProfilePicture { get; set; }
        public bool IsOnline { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public long TotalMessagesSent { get; set; }
        public long TotalTicks { get; set; }
        public Nullable<System.DateTime> LastTimeLoggedIn { get; set; }
        public string EmailAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message_Record> Message_Record { get; set; }
    }
}
